name: Publish to npm

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.7.0'
          registry-url: 'https://registry.npmjs.org'

      - name: Debug Information
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo "Package.json contents:"
          cat package.json

      - name: Install dependencies
        run: npm ci

      - name: Check version and publish
        run: |
          PUBLISHED_VERSION=$(npm view keyframe-stats version || echo "0.0.0")
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          if [ "$PUBLISHED_VERSION" != "$PACKAGE_VERSION" ]; then
            npm publish
            echo "Published new version $PACKAGE_VERSION"
          else
            echo "Version $PACKAGE_VERSION already published. Skipping."
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Output npm logs if publish failed
        if: failure()
        run: |
          echo "npm logs:"
          cat /home/runner/.npm/_logs/*-debug.log