name: Publish to npm

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm test
      - name: Check version and publish
        run: |
          PUBLISHED_VERSION=$(npm view keyframe-stats version)
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          if [ "$PUBLISHED_VERSION" != "$PACKAGE_VERSION" ]; then
            npm publish
          else
            echo "Version unchanged. Skipping publish."
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}